[package]
name = "aoc2024"
version = "1.0.0"
edition = "2021"
description = "Advent of Code 2024 CLI app"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
regex = "1.11.1"

[dev-dependencies]
assert_cmd = "2.0"
